version: '3'
services:
  transmission-daemon:
    image: ${DOCKER_REGISTRY}monstrenyatko/transmission-daemon
    container_name: transmission-daemon
    environment:
     - APP_UID=${TRANSMISSION_DAEMON_UID}
     - APP_GID=${TRANSMISSION_DAEMON_GID}
    restart: unless-stopped
    ports:
      - 9091:9091
    volumes:
      - transmission-daemon-config:/var/lib/transmission/config
      - ${TRANSMISSION_DAEMON_DOWNLOADS}:/var/lib/transmission/downloads

volumes:
  transmission-daemon-config:
